### ISSUE TITLE
足し算で足す数が負の数になってる

### ISSUE THREAD

**Issue by tabe0127** [Utsugi0101/git-training-2024-09-18#5]
## 操作手順
* 〜したら
* 〜になった
空白+1=-1, 空白+2=-2, ...になった

## 本来の想定
* 〜したら
* 〜になってほしい
空白+1=1, 空白+2=2, ...になってほしい

## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン

**Comment by inucat** [comment]
#2 と重複。Closing
